language: ruby
rvm:
  - 2.0.0
  - 2.1.4
  - rbx
  - jruby-head

matrix:
  allow_failures:
    - rvm: jruby-head

addons:
  code_climate:
    repo_token: 20a1139ef1830b4f813a10a03d90e8aa179b5226f75e75c5a949b25756ebf558
